import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import NavBar from "../components/NavBar/NavBar";
import {useState} from "react";
export default function Home() {
    const [sideBarOpen, setSideBarOpen] = useState(false);
    const sideBarButtonHandler = () => {
        setSideBarOpen(!sideBarOpen);
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/public/favicon.ico"/>
            </Head>
            <NavBar sidebar={sideBarButtonHandler} />
        </div>
    )
}
