import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import NavBar from "../components/NavBar/NavBar";
import {useState} from "react";
import SideBar from "../components/SideBar/SideBar";
import Card from "../components/Card/Card";
import Message from "../components/Message/Message";

export default function Home() {
    const [sideBarOpen, setSideBarOpen] = useState(false);
    const sideBarButtonHandler = () => {
        setSideBarOpen(true);
    }
    const dropButtonHandler = () => {
        setSideBarOpen(false);
    }


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/public/favicon.ico"/>
            </Head>

            <NavBar sidebarHandler={sideBarButtonHandler}/>
            <SideBar display={sideBarOpen}/>
            <div onClick={() => setSideBarOpen(false)}>
                <Message/>
                <Card/>


            </div>

        </div>
    )
}
